### ISSUE TITLE
Request - Swipe on spacebar to move cursor

### ISSUE THREAD

**Issue by jonahclarsen** [SimpleMobileTools/Simple-Keyboard#110]
I recently switched to this keyboard from the other FOSS SimpleKeyboard app, and I much prefer this one, both because of the integrated emoji keyboard, which that is committed to not offering for some reason, and the design/keyboard layout.

However, one feature that I really miss is swiping left or right on the spacebar to move the cursor along the text.

This (along with removing the clipboard row) would make this the absolute perfect keyboard app for me.

Thanks devs for your great work on this project!

**Comment by tibbi** [comment]
you can already do it, just long press the space first.
