### ISSUE TITLE
Feature Request: Text Cursor Control

### ISSUE THREAD

**Issue by Saijin-Naib** [SimpleMobileTools/Simple-Keyboard#111]
SwiftKey implements this by a tap+hold on the spacebar, and then you drag your finger over the keyboard to reposition the text cursor.

This is way less fiddly than trying to fight Android's logic on this.

**Comment by tibbi** [comment]
you can already do that by long pressing space, then moving your finger to sides

**Comment by Saijin-Naib** [comment]
Awesome!

What do you think about allowing moving the cursor up and down lines of text? It would be great for larger bodies of text.

Also, it's not very discoverable... Would you consider an arrows/compass rose like overlay for the spacebar so folks know to try?

**Comment by tibbi** [comment]
Im not a fan of recognizing up/down gestures on the spacebar, could be too sensitive

**Comment by Saijin-Naib** [comment]
I'm assuming that means expanding the drag area to the rest of the keyboard is a no - go, right?

That would likely provide more than enough vertical area to have good, linear sensitivity.
