### ISSUE TITLE
Feature Request: Add More Punctuation To Popup Menu For Period Key

### ISSUE THREAD

**Issue by Saijin-Naib** [SimpleMobileTools/Simple-Keyboard#112]
It'd be really nice for sentence composition if we didn't need to jump into the keyboard for punctuation, but rather could get most sentence ending punctuation from tap/hold on period.

So, there would be comma, semicolon, colon, question mark, exclamation mark, and maybe hyphen/dash.

**Comment by vserbu** [comment]
I agree, that I miss that feature the most in this really great keyboard!
