### ISSUE TITLE
Add Finnish keyboard layout

### ISSUE THREAD

**Issue by laurivehkaoja** [SimpleMobileTools/Simple-Keyboard#114]
App doesn't currently have support for either Finnish or Swedish QWERTY keyboard layouts which makes typing characters such as `ä`, `ö` and `å` annoying to type as they are behind other characters.

**Comment by laurivehkaoja** [comment]
Here is a reference image of the Finnish keyboard layout if needed

![finnish_keyboard_layout](https://user-images.githubusercontent.com/74737645/208635810-3148cf64-4ab1-46eb-a75f-6796d0cab6d5.jpg)

**Comment by Merkost** [comment]
Swedish keyboard was added here: https://github.com/SimpleMobileTools/Simple-Keyboard/pull/174. @tibbi, the issue could be closed

**Comment by chihung93** [comment]
Hi @laurivehkaoja, 

Finnish or Swedish QWERTY keyboard is now supported, Do you have any difficulty using it.?

Thanks

**Comment by chihung93** [comment]
Hi @tibbi , I think we can close this PR. Thanks.
