### ISSUE TITLE
Clipboard history Enhancement

### ISSUE THREAD

**Issue by Pantyhose-X** [SimpleMobileTools/Simple-Keyboard#118]
Please don't auto clean `Current` 
Please set the history retention time to No limit by default
I forgot `PInned` and lost my important password

**Comment by tibbi** [comment]
we arent autocleaning anything, there are no limits either.

**Comment by Pantyhose-X** [comment]
> we arent autocleaning anything, there are no limits either.

`Current` keeps only one text, loop override ?

https://user-images.githubusercontent.com/42504385/209658883-508fa5c0-dc93-46b0-aa88-149795b22666.mp4

* I forget that the `PInned` text will be lost

**Comment by tibbi** [comment]
thats how it is supposed to work, there is no history

**Comment by Pantyhose-X** [comment]
> * PInned

We need history, and we're going to replicate some important stuff. Forgetting `PInned` can be bad for us.

**Comment by Pantyhose-X** [comment]
> thats how it is supposed to work, there is no history

We need history, and we're going to replicate some important stuff. Forgetting `PInned` can be bad for us.
