### ISSUE TITLE
v5.0.1 APK is unsigned

### ISSUE THREAD

**Issue by IzzySoft** [SimpleMobileTools/Simple-Keyboard#12]
Could you please sign the APK attached to the release? My updater just alerted me the APK attached to v5.0.1 is unsigned. I checked and confirm:

```
DOES NOT VERIFY
ERROR: Missing META-INF/MANIFEST.MF
package: name='com.simplemobiletools.keyboard' versionCode='2' versionName='5.0.1' compileSdkVersion='30' compileSdkVersionCodename='11'
```

Thanks in advance! My updater will check again tomorrow around 18:20 UTC.

**Comment by tibbi** [comment]
you mean on Github or where?

**Comment by IzzySoft** [comment]
Did you attach it to some other release as well? :smile: I mean here: https://github.com/SimpleMobileTools/Simple-Keyboard/releases/tag/5.0.1 Thanks for caring!

**Comment by tibbi** [comment]
right, I updated it, thanks. Thats why I shouldnt upload new versions at midnight...

**Comment by IzzySoft** [comment]
Thanks, that worked out fine! The only thing my updater complained about now is:

```
com.simplemobiletools.keyboard: checking locale 'en-US'
com.simplemobiletools.keyboard: only PNG and JPEG are supported for graphics, skipping 'icon.xcf'
com.simplemobiletools.keyboard: only PNG and JPEG are supported for graphics, skipping 'orange_feature_graphic.xcf'
com.simplemobiletools.keyboard: only PNG and JPEG are supported for graphics, skipping 'square.xcf'
```

No big deal here as the "right ones" are there. IIRC F-Droid had some issues with that, while my updater simply ignores them. Btw, there's an `english/` directory inside `/fastlane/metadata/android/en-US/images/phoneScreenshots/` which doesn't belong there either. Just to let you know in case you've missed it.

5.0.1 will show up in my repo with the next sync then (tomorrow, around 19:00 UTC).

**Comment by tibbi** [comment]
ye I have my images stored in a whole different way, the fastlane structure is not maintainable. Im just not pushing all those files on github.

**Comment by IzzySoft** [comment]
OK, all fine then. My updater simply skips what doesn't fit (the logging above was just due to enabling debug log to see if there are issues), and I hope F-Droid does the same (there were some issues in the past; so should pictures not show up, let's remember this one here as a pointer to what to look for in F-Droid logs then – which hopefully won't be needed).
