### ISSUE TITLE
general improvements

### ISSUE THREAD

**Issue by rgndxzzk** [SimpleMobileTools/Simple-Keyboard#121]
1. option to disable auto capitalization
2. option to have the numbers have their own row of keys instead of being hidden under the top row of letters
3. more flexibility with height options
4. deadzones, such has having the keyboard be higher
5. when holding down on any number, also show [superscript and subscript numbers](https://unicode-table.com/en/sets/superscript-and-subscript-numbers/)
6. option to hide clipboard preview
7. add a search on the emoji panel
8. a spacebar on the emoji panel
9. quick access to preferred languages

**Comment by tibbi** [comment]
report things one by one please, if it hasnt been reported already. Some things are already reported.
