### ISSUE TITLE
[Feature Request]: More Height options and/or User defined heights

### ISSUE THREAD

**Issue by heschy2** [SimpleMobileTools/Simple-Keyboard#126]
Hello, I really like the application but for me the minimum available height is still to big, adding new options would be cool (e.g.: extra large and extra small).

It could also be a great feature to use a user defined height so that the user chooses a specific amount of pixels by himself/herself.

**Comment by starsep** [comment]
I agree. `Small` is quite large with 20:9 screen ratio
