### ISSUE TITLE
Pop on keypress is confusing

### ISSUE THREAD

**Issue by MaxsimLionel** [SimpleMobileTools/Simple-Keyboard#145]
It is confusing to me because the popup does not connect to the key that is tapped. It just hovers above it. It would be less confusing if it connected to the keg that is tapped, like in openboard.
thank you.

**Comment by tibbi** [comment]
not sure what you mean, what is confusing there?

**Comment by MaxsimLionel** [comment]
On the latest update, it is fixed for me by going into settings and enabling "Show key borders"
