### ISSUE TITLE
The numpad layout should have a period (comma as alternative option)

### ISSUE THREAD

**Issue by Grosskopf** [SimpleMobileTools/Simple-Keyboard#147]
When typing in Bills I just received into Moneybuster I often use the numpad to input the amount I paid and I'm very german about this, so I type in the cents as well :D this is however increasingly hard to do since I switched to the simple keyboard, I now allways have to switch between modes mid typing. Can you please make it possible that i have an extra key for the "."?  :)

**Comment by tibbi** [comment]
it is already there

**Comment by Grosskopf** [comment]
![signal-2023-02-18-101432](https://user-images.githubusercontent.com/20133478/219852378-c1626ef9-e419-4ab5-899d-d6a1f3313bb0.png)
That's odd, this is how it looks on my device, no  period in the Numpad layout on version 5.4.1 not in german, not in english qwerty not in english qwertz

**Comment by tibbi** [comment]
hm, it should work in 5.4.2 then

**Comment by Grosskopf** [comment]
Oh wow, I did not notice, that the Numpad layout was so new and this app is so actively developed at the Moment :) thanks a lot

**Comment by tibbi** [comment]
I fixed the issue for numeric keypad, but didnt notice that the phone numbers use a different one
