### ISSUE TITLE
entry form cannot be finished

### ISSUE THREAD

**Issue by TheFlipside** [SimpleMobileTools/Simple-Keyboard#16]
A little hard to describe but some apps have forms to enter, like a list of numbers, and at the end there is no confirm button within the UI but the task is done by the "confirm" button on the keyboard which usually shows up on the bottom right.

The problem I encounter with Simple Keyboard in at least one app i know of is that the confirm button does not finish the entry of the form, nothing happens and I have no other way to process, I need to switch to another keyboard and return to the app and then I'm able to confirm the form.

The app in question is [MediLog](https://f-droid.org/en/packages/com.zell_mbc.medilog/), the problem can be reproduced by having Simple Keyboard set to the default keyboard and then opening the MediLog app, enter 3 values and try to confirm with the keyboard's confirm button.

Simple Keyboard version: 5.0.2

**Comment by tibbi** [comment]
I fixed a similar case, not exactly this one. Reopen the issue if it wont be fixed in 5.0.4.

**Comment by TheFlipside** [comment]
I can confirm the problem is resolved
