### ISSUE TITLE
Fuzzy Dictionary / Auto Correction

### ISSUE THREAD

**Issue by Pixelschleuder** [SimpleMobileTools/Simple-Keyboard#160]
It would be nice to have a fuzzy dictionary which offers corrected words when there is a typo, shown in the (cliboard) bar of the keyboard that corrects a word when getting tapped.

**Comment by tibbi** [comment]
that isnt on the roadmap

**Comment by Justauser0** [comment]
> that isnt on the roadmap

How about in future
