### ISSUE TITLE
Add a Caps Lock function

### ISSUE THREAD

**Issue by sudwhiwdh** [SimpleMobileTools/Simple-Keyboard#171]
Sometimes makes writing easier.

**Comment by tibbi** [comment]
it is already there at double pressing shift

**Comment by sudwhiwdh** [comment]
O thank you. Do you have any idea how this function could become discoverable? I have not known it until now.

**Comment by sudwhiwdh** [comment]
O thank you. Do you have any idea how this function could become more discoverable?
I have not known about the function until now.

**Comment by tibbi** [comment]
that is the expected behaviour, we dont plan changing it

**Comment by sudwhiwdh** [comment]
The expected behaviour is that the feature is not self-explanatory? On my laptop, there is a separate key for this. In Simple Keyboard, the function is located on the shift key.
And yes, I am also happy that the function already exists. I just wonder if users know about it.

**Comment by sudwhiwdh** [comment]
I am happy that the function already exists. I just wonder if users know about it.

**Comment by tibbi** [comment]
of course they do, thats how all keyboards have it

**Comment by sudwhiwdh** [comment]
You mean on Android keyboards, right?
On my computer keyboard there is a separate physical key for it.

**Comment by sudwhiwdh** [comment]
You mean on Android keyboards?
On my computer keyboard there is a separate physical key for it.

**Comment by tibbi** [comment]
ye, android keyboards
