### ISSUE TITLE
Wrong cursor position after clipboard pasting  

### ISSUE THREAD

**Issue by Merkost** [SimpleMobileTools/Simple-Keyboard#175]
When you paste something from the clipboard the cursor position remains unchanged, but it should be at the end of the pasted text.

**Comment by tibbi** [comment]
it works just like that to me, havent you tested some modified app version?

**Comment by Merkost** [comment]
> it works just like that to me, havent you tested some modified app version?

Nope, just the google play version

**Comment by Merkost** [comment]
https://github.com/SimpleMobileTools/Simple-Keyboard/assets/56008710/46289597-7e78-4be0-bf83-56dff0efd03a

**Comment by tibbi** [comment]
you can take a look at it then

**Comment by tibbi** [comment]
@Merkost this has been solved already, or not?

**Comment by Merkost** [comment]
> @Merkost this has been solved already, or not?

Nope, the issue still exists. Will take a look tomorrow👌

**Comment by tibbi** [comment]
ok, I just wasnt sure, created a task for it
