### ISSUE TITLE
Keyboard settings not applied after startup

### ISSUE THREAD

**Issue by JustScott** [SimpleMobileTools/Simple-Keyboard#191]
* Android Version **13**
* App Version **5.4.3**

None of my keyboard settings are applied until after the phone starts up ( after the first login ), as in the keyboard works as if I just downloaded it.

I'm not sure if this is just a bug, or if it's just not possible to apply user settings before the phone is past the initial login.

Thanks for all you guys do!

**Comment by tibbi** [comment]
thats how it is supposed to work, we cannot access any settings before the user logs in the first time after a device startup
