### ISSUE TITLE
lock screen settings

### ISSUE THREAD

**Issue by tdpo2** [SimpleMobileTools/Simple-Keyboard#198]
Default-ish settings? e.g. Vibration on. When supposed to be off. Works normally in other cases.

**Comment by tibbi** [comment]
sadly the lock screen keyboard cannot access the config values, only after unlocking

**Comment by tdpo2** [comment]
How? It worked in the past.

**Comment by tibbi** [comment]
not really, it couldnt

**Comment by tdpo2** [comment]
Well. I don't know but how. But keys didn't vibrate on press.

**Comment by tdpo2** [comment]
With version 5.4.5. Issue is fixed. What did you change?
