### ISSUE TITLE
5.4.3 no longer works with Termux

### ISSUE THREAD

**Issue by Monstanner** [SimpleMobileTools/Simple-Keyboard#200]
With the update to 5.4.3, no input is recognized anymore in Termux. Exceptions are: Return, Backspace and Emojis. 

**Tested versions:**

| Version  | GitHub | F-Droid |
| :-------------: | :-------------: | :-------------: |
| 5.4.5  | Broken  | not yet Released in the F-Droid Repo |
| 5.4.4 | Broken | not yet Released in the F-Droid Repo |
| 5.4.3 | Broken | Broken |
| 5.4.2 | Working | Working |

**Expected behavior:**

All inputs should be recognized by Termux again as in 5.4.2.

**Device Info:**

Device: Nokia 6.1
OS: Android 10 Vanilla

**Comment by tibbi** [comment]
what do you mean, how to reproduce it?

**Comment by Monstanner** [comment]
> what do you mean, how to reproduce it?

I mean that I can no longer write in the Termux app with this keyboard since 5.4.3 and above. Other apps seem to work normally with the keyboard. To reproduce it: Download the Termux app from the F-Droid Store and install it. Then write something with this keyboard. It doesn't work, except as described above, The Return, Backspac and Emoji key / emojis.

**Comment by Test-osss** [comment]
I have same problem on Samsung A12 (Android 13)

**Comment by tibbi** [comment]
test the latest version from Github please, it is at https://github.com/SimpleMobileTools/Simple-Keyboard/releases . It is the same version that will get to f-droid

**Comment by Monstanner** [comment]
> test the latest version from Github please, it is at https://github.com/SimpleMobileTools/Simple-Keyboard/releases . It is the same version that will get to f-droid

If I'm meant. I did. That's why in my first post there is a table with the tested versions and where I got them from. 5.4.3, 5.4.4 and 5.4.5 all have this bug.

**Comment by tibbi** [comment]
right sorry, didnt notice the Github column

**Comment by dhammel** [comment]
I too am having this issue with 5.4.3 and onward. Currently having to use a different keyboard when using Termux. If there is anything I can do to help debug this issue, I will.

**Comment by Monstanner** [comment]
I forget to note that in addition to Return, Backspace and Emojis, the clipboard/paste also works. Sorry.
