### ISSUE TITLE
Keyboard sometimes covers whole screen on tablets

### ISSUE THREAD

**Issue by user44000** [SimpleMobileTools/Simple-Keyboard#218]
The keyboard covers the whole screen in landscape mode in certain areas of apps.
1. Simple Keyboard
![Screenshot_20230715-003739_Keyboard](https://github.com/SimpleMobileTools/Simple-Keyboard/assets/138707369/a32c123e-4144-43d2-b446-5e3eb2b0a1a7)
2. FOSS Browser
![Screenshot_20230715-010523_FOSS Browser](https://github.com/SimpleMobileTools/Simple-Keyboard/assets/138707369/7ead998b-9989-44d5-9bf2-c3d191201d26)
3. FOSS Browser
![Screenshot_20230715-005427_FOSS Browser](https://github.com/SimpleMobileTools/Simple-Keyboard/assets/138707369/7e7896e1-253f-4915-a650-0eda58d45748)

**Comment by tibbi** [comment]
how are other keyboards shown?

**Comment by user44000** [comment]
This is what OpenBoard looks like.
![Screenshot_20230716-012640_FOSS Browser](https://github.com/SimpleMobileTools/Simple-Keyboard/assets/138707369/f1adb51b-50b2-447a-85c5-4e23a8eb1144)
![Screenshot_20230716-012720_FOSS Browser](https://github.com/SimpleMobileTools/Simple-Keyboard/assets/138707369/178eeb78-485e-40b6-b213-30385aedbf5a)

**Comment by tibbi** [comment]
thats a different layout..

**Comment by user44000** [comment]
OpenBoard doesn't cover the whole screen like Simple Keyboard does. The other Simple Keyboard app also doesn't cover the whole screen.
