### ISSUE TITLE
Report Bug : Delete key not Working (Exagear Windows Emulator)

### ISSUE THREAD

**Issue by ricoyp96** [SimpleMobileTools/Simple-Keyboard#222]
This bug since v5.4.3

**Comment by tibbi** [comment]
try updating to 5.4.7

**Comment by ricoyp96** [comment]
> try updating to 5.4.7

Still not working sir :(

**Comment by ricoyp96** [comment]
> try updating to 5.4.7

All keys are working except delete key

**Comment by tibbi** [comment]
how to reproduce it?

**Comment by ricoyp96** [comment]
> how to reproduce it?

To reproduce it: Download the Termux app from the F-Droid Store and install it. Then write something with this keyboard on Exagear Windows Emulator App. All keys are working but not for Delete key

**Comment by ricoyp96** [comment]
> how to reproduce it?

To reproduce it: Download Exagear Windows Emulator on YouTube and install it. Then write something with this keyboard. All keys are working, but delete key doesn't work

**Comment by tibbi** [comment]
what is exagear windows emulator? Can you give links too?

**Comment by ricoyp96** [comment]
> what is exagear windows emulator? Can you give links too?

https://www.youtube.com/watch?v=DUZPAoTzwFI&t=0

**Comment by tibbi** [comment]
man just tell some steps for reproducing the issue, nobody will watch a 5 minutes video everytime at working on it

**Comment by ricoyp96** [comment]
> man just tell some steps for reproducing the issue, nobody will watch a 5 minutes video everytime at working on it
Never mind, i put apk+obb Exagear Windows Emulator link here,
apk link : https://ricorer.xtgem.com/exagear/apk
obb link : https://ricorer.xtgem.com/exagear/obb

(choose the latest version)

**Comment by tibbi** [comment]
those links redirect to some shady websites, doesnt sound like an issue that can happen at casuall used apps... At least people havent reported it yet, will close this one until some clear steps for reproducing the issue.
