### ISSUE TITLE
features request

### ISSUE THREAD

**Issue by ionuttbara** [SimpleMobileTools/Simple-Keyboard#231]
Dear Developer, can you add 2 things in your app?
first showning images fron clipboard. its very handy feature and send images from keyboard.
second feature is customize keyboard like Samsung KeysCafé.
Add keys, remove keys , rows and more. adding emoji on top of the keyboard and text into single key.

**Comment by tibbi** [comment]
Hey, that isnt really on the roadmap. Anyway, report things one by one in the future. Thanks
