### ISSUE TITLE
Please add Bengali language.

### ISSUE THREAD

**Issue by iBabu007** [SimpleMobileTools/Simple-Keyboard#24]
Please sir add Bengali language. Like gboard.
It is too good but i missed some features.
Please add Bengali language.

![keyboard Bengali 2](https://user-images.githubusercontent.com/65340361/154935338-fccede2f-bd43-46d9-a5d4-578e2aa0e35a.png)

![keyboard bengali](https://user-images.githubusercontent.com/65340361/154935344-25cb1cf2-6693-4f5b-a143-e07efa43c7db.png)

**Comment by suttod** [comment]
Closed by #83
