### ISSUE TITLE
BLANK TEXT CANNOT BE COPIED THAT'S A PROBLEM IMMEDIATELY UPDATE

### ISSUE THREAD

**Issue by MelisaTanaga** [SimpleMobileTools/Simple-Keyboard#244]
I only need this update when I copy letters and numbers along with spaces, only the blank spaces are not copied, only the letters and numbers are saved on the clipboard.

**Comment by tibbi** [comment]
what do you mean, can you tell steps for reproducing?

**Comment by MelisaTanaga** [comment]
what this means is that if you copy, say the example text "127.0.0.1 " along with blank spaces, it is also copied, it is not saved on the clipboard, only numbers and letters, for example "tried " I also copied blank spaces but it is not saved on the clipboard, only letters, immediately correct this deficiency.

**Comment by MelisaTanaga** [comment]
When will the feature update be, I've been waiting for it, if you don't understand what I mean, try copying a blank space, it will definitely not be saved on the clipboard
