### ISSUE TITLE
Feedback on app usability

### ISSUE THREAD

**Issue by fbsz** [SimpleMobileTools/Simple-Keyboard#246]
Hello, simple keyboard is one of the good free software for android.
There could be some changes I wish to suggest
1. Material theme support, although the app supports. I like the theme of GBOARD which is also material you.
2. Improvements on haptic effects when typed
3. Suggestions

**Comment by tibbi** [comment]
1. material you is already there, improving it is on the roadmap
2. haptic is handled by the system
3. suggestions arent planned
