### ISSUE TITLE
Locked customise color on playstore version

### ISSUE THREAD

**Issue by kik-btaski** [SimpleMobileTools/Simple-Keyboard#250]
When i install playstore version, its customise color is locked and asks for purchase. But in fdroid version, its not the case. Initially i thought playstore version may be copycat but confirmed its not.

 Why playstore have customise color locked ?

**Comment by tibbi** [comment]
you need Simple Thank You to have everything unlocked. F-droid doesnt support payments, so we kept it unlocked there as Thank You is free anyway.
