### ISSUE TITLE
[BUG] French accent cannot be selected correctly

### ISSUE THREAD

**Issue by pioupia** [SimpleMobileTools/Simple-Keyboard#251]
With the QWERTY Keyboard, if you try sometimes to select the french "e" accent (é or è), it'll print ú or or t with an accent or á and many other strange things. Its append with other accent too.

**How to reproduce the bug** ?
For the moment, I don't really understand when exactly this bug append, but I though it when you type the `a` french accent (à) then you try to write a e french accent (é or è).

For example:
Try to type: `Je vais à l'école` (I'm going to school), it'll work because I don't know.
But try : `Dans les boîtes en métal` (In the metal boxes), it'll write:
`Dans les boîtes en m8tal` because you can't select other thing than 8.

If you write: `î` then you try to put an accent on `e`, it will just print ì or í or ï or something like that.

I'm sorry for these poor information, but I don't know how this app work because I didn't read the code, so I don't know where the problem is exactly and when it's append.

**Comment by dmitriy-chernysh** [comment]
I was able to reproduce it. Steps:

1. Open the keyboard in French (AZERTY)
2. Long press on 'a' and select any symbol
3. Long press on 'e' and select any symbol
4. Try to long press on 'a' and you cannot select any symbol there, and it types the symbol from the layout you saw at point 3.

It seems like the current symbols set is overlapped by the previous one that is no longer visible.
Short video  https://youtube.com/shorts/N1Jauj-N78I

I'm trying to fix.
