### ISSUE TITLE
Vietnamese key layout is missing in the app 

### ISSUE THREAD

**Issue by dmitriy-chernysh** [SimpleMobileTools/Simple-Keyboard#256]
App version 5.4.8
Language is available to be selected in the app but it references to a default English layout ```R.xml.keys_letters_english_qwerty.xml```.

```R.xml.keys_letters_vietnamese_telex.xml```  is missing

![image](https://github.com/SimpleMobileTools/Simple-Keyboard/assets/5750211/f5fbddca-f3d5-4771-87f4-234c1cd203af)

**Comment by tibbi** [comment]
vietnamese works differently, it doesnt have a casual layout file
