### ISSUE TITLE
Feature request: can you add something to choose the key press delay for accented letters?

### ISSUE THREAD

**Issue by zShxck720** [SimpleMobileTools/Simple-Keyboard#269]
In Italian we use a lot of accented letters so it would be nice to have something to reduce the key press delay to type an accented letter (for example in another keyboard I have this set to 190ms). 
It would also be nice if we could choose the default accented letter that pops up or if the keyboard could remember the last utilized one for each vocal (for example in Italian we use these accented letters: à, è, ì, ò, ù but the defaul one is ê, ï, õ, û).

**Comment by tibbi** [comment]
that isnt really on the roadmap
