### ISSUE TITLE
Add emojis

### ISSUE THREAD

**Issue by vunhiem96** [SimpleMobileTools/Simple-Keyboard#27]
The app is missing this button

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
This appears to he silly. Why support solely the latin alphabet, Eastern Arabian numerals, random punctuation and select pictography? The keyboard shall become a bad character map. We should ideally adcertain how to type any character rather than specifically support x block of Unicode.

**Comment by jcperil** [comment]
What's the update on this?

**Comment by tibbi** [comment]
an initial version of emojis will be added in 5.3.0, improvements will be eventually added too
