### ISSUE TITLE
Switch language

### ISSUE THREAD

**Issue by vunhiem96** [SimpleMobileTools/Simple-Keyboard#34]
hello, hope you can add a language switch right on the keyboard

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Does this keyboard support languages except English? I am not able to switch within the configurative page of the application.

**Comment by tibbi** [comment]
you can change language in the app settings

**Comment by nandlab** [comment]
Please add a switch on the keyboard to quickly change the language.
If you use a cyrillic keyboard, you have to switch between english and cyrillic very often. Having to open the settings every time is very inconvenient.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@tibbi, if this is added, please allow it to be optional. I expect that customisation of the layout of the keyboard would allow this well, rather than addition of a toggle merely for this.

**Comment by DreitTheDragon** [comment]
Just for inspiration, Hacker's Keyboard had option to choose more languages in menu (checkboxes) and then switch by swiping on spacebar to left or right. There was also Fn key next to spacebar to switch into alternative layout. I just tried that spacebar swipe and it doesn't seem like a bad idea. Of course I'm not a programmer so I have no idea how difficult it would be to implement. Or maybe long press on spacebar and popup with keyboards to choose from?

**Comment by smaragdus** [comment]
The keyboards I have used either have a language key (Gboard, FlorisBoard) or use space key as a slider to switch language (SwiftKey). I prefer the second method as it does not waste space. For me a way to quickly switch languages is the most needed feature in Simple Keyboard.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
I expect a long-press on the keyboard to type additional spaces. Consequently, I suggest addition of a new key.

**Comment by 7ArxS2PrqAUF9Gom** [comment]
This keyboard definitely needs this feature. It shouldn't be hard to implement. Having to use settings to switch between languages is very cumbersome, not simple.
