### ISSUE TITLE
Proposals for multilingual support

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [SimpleMobileTools/Simple-Keyboard#37]
It would be awesome to make this app able to input various language texts. To get the implementation, I have two proposals for this.
1. Integrate supports for multiple languages into the app itself, just likes Gbord or SwiftKey, however this would make the app much more larger, and being very hard work to you.
2. Provides some APIs into Simple Keyboard main app, then provides some plug-in APKs to give support for specific language, once the stub APK is installed, the settings page would provide options to switch and configure, if you published the API documentations, other developers would soon give a hand to support, so this app would be possible to support multiple language and takes fewer space.

So WDYT?

**Comment by tibbi** [comment]
that is way too advanced for our app, dont expect having any dictonaries
