### ISSUE TITLE
Spanish Layout - Weird left margin in the second row

### ISSUE THREAD

**Issue by margual56** [SimpleMobileTools/Simple-Keyboard#38]
Introduced in [commit 97807c9c84ab361d2c490a165d54a3a04e84639f](https://github.com/SimpleMobileTools/Simple-Keyboard/pull/33/commits/97807c9c84ab361d2c490a165d54a3a04e84639f), it adds a 5% left margin to a row that already fills the entire width.

## How it looks:
<img src="https://user-images.githubusercontent.com/30444886/162147511-e780b10e-42a1-4829-b69f-13226a7d87d2.jpg" width=200/>

## How it should look:
(SwiftKey as an example)
<img src="https://user-images.githubusercontent.com/30444886/162147569-35c6f5c1-a6dd-4ee2-9c6c-ee49b7447118.jpg" width=200/>

**Comment by tibbi** [comment]
right, my bad. Didnt notice the extra key
