### ISSUE TITLE
don't limit clipboard

### ISSUE THREAD

**Issue by Gamefire238** [SimpleMobileTools/Simple-Keyboard#44]
It would be great if we could store more clipboards without tagging them.

I copied several titles using this keyboard, and pressed the clipboard, hoping everything I copied was there, and apparently I only got one last title I copied!, I Think like I'm just wasting my time :( why not five or six? why only one!

Hope this is fixed in the next version

**Comment by tibbi** [comment]
that is way too advanced, just pin the items you want to use often
