### ISSUE TITLE
First letter lower case (Feature Request)

### ISSUE THREAD

**Issue by R1yuu** [SimpleMobileTools/Simple-Keyboard#48]
An option to choose whether the first typed letter should automatically be upper case or not would be nice (A checkbox for example).

**Comment by tibbi** [comment]
it is the "Capisalise the first word of each sentence" option in Gboard right?

**Comment by R1yuu** [comment]
Exactly! :)

**Comment by tibbi** [comment]
has been added in 5.4.5
