### ISSUE TITLE
Please make lithuanian keyboard option

### ISSUE THREAD

**Issue by VGumbakis** [SimpleMobileTools/Simple-Keyboard#52]
Lithuanian letters are Ą, Ę, Ė, Į, Ų, Ū, Č, Š, Ž ( works both capital and lower case and can be the in line  on top of the keyboard) everything else is latin, qwx- not lithuanian, but can be left ( so there will be no need to change to english )

**Comment by Naveen3Singh** [comment]
<img src="https://user-images.githubusercontent.com/36371707/184505951-42fad22d-63f1-4a70-afe7-e31cc930a588.png" width="264" /> <img src="https://user-images.githubusercontent.com/36371707/184505972-406dbe01-7642-455b-9923-5ddb450b4dea.png" width="264" />

In Gboard, I selected Lithuanian but the above is all that I see. The letters you mentioned only show up in the popups on long press. Is that what is required?

or is the keyboard layout different in Lithuanian? Could you send a screenshot of a Lithuanian soft keyboard?

(Simple-Keyboard also has this long-press feature but not all of the Lithuanian letters are there)

**Comment by suttod** [comment]
Closed by #83
