### ISSUE TITLE
Make an option to show digits on top of the keyboard

### ISSUE THREAD

**Issue by VGumbakis** [SimpleMobileTools/Simple-Keyboard#53]
Like in added picture
![Screenshot_20220617-134346~2](https://user-images.githubusercontent.com/23702562/174283913-bc9e7f9d-7cc0-42fc-bbc7-0b5f3e5caa08.png)

**Comment by gargamel17** [comment]
Yes, it is more user friendly to have direct access to numbers

**Comment by MaCroX95** [comment]
Yes please! This would be a great quality of life improvement!

**Comment by tibbi** [comment]
it has already been added in 5.4.1
