### ISSUE TITLE
Long press duration setting (Feature request)

### ISSUE THREAD

**Issue by DreitTheDragon** [SimpleMobileTools/Simple-Keyboard#54]
**Introduction**:
I'm long term user of [Hacker's Keyboard](https://github.com/klausw/hackerskeyboard) and I'd like to switch to Simple keyboard since original app is not developed anymore and it got broken in newer Android versions. I actually have to use even 2016 version since newer ones are broken even more for me.
One main thing stops me from switching to Simple Keyboard at the momnet - I'm used to really short delay between pressing key and popup appearing above keys. I think original delay in HK is about 400 ms and over time I really got used to 160 ms. There is slider in settings to change delay depending on what you prefer (honestly number input field would be probably better). Using any different keyboard (including SK) feels really uncomfortable for me as it forcefully limits my typing speed and I'm not able to simply change it.

**Request**:
Would it be possible to add option to change "long press" duration before popup appears in menu?

Thank you in advance.

**Comment by suttod** [comment]
Hi, the app uses system defaults. You can change it globally in Settings > Accessibility > Touch and hold delay.
