### ISSUE TITLE
pin manage clipboard items enhancement

### ISSUE THREAD

**Issue by Pantyhose-X** [SimpleMobileTools/Simple-Keyboard#57]
Default All copy text is saved to manage clipboard items.
Pin text and do just one thing, sort the text to the top.
Clipboard adds delete function.

**Comment by tibbi** [comment]
Im not sure what you mean, you can already pin wanted clipboards, even reorder them.

**Comment by Pantyhose-X** [comment]
> Im not sure what you mean, you can already pin wanted clipboards, even reorder them.

@tibbi clipboard I use it to store your important stuff like passwords, website addresses. If I forget Pinned， it gets deleted, which is very bad.
