### ISSUE TITLE
Add Japanese language

### ISSUE THREAD

**Issue by jcperil** [SimpleMobileTools/Simple-Keyboard#58]

**Comment by Naveen3Singh** [comment]
Hi!
Are you talking about the qwerty Latin layout ([rōmaji](https://en.wikipedia.org/wiki/Romanization_of_Japanese)) or the 12 keys layout with Japanese characters?

**Comment by jcperil** [comment]
Closing this as Japanese requires a special input logic that doesn't fit into Latin AOSP keyboard.

**Comment by nucspl** [comment]
Couldn't [Mozc](https://github.com/google/mozc) be integrated with Simple Keyboard?
