### ISSUE TITLE
Set default theme to Black & White

### ISSUE THREAD

**Issue by bzark** [SimpleMobileTools/Simple-Keyboard#67]
I use this keyboard for my assisted living home because it is so simple and keeps the people from hitting all the wrong keys.  I build the app from code and install on it on the phone but I would like to set the default theme to Black and White because this is easier for them to see.  I tried changing the theme in sytles.xml and had no luck.  I looked through the code and couldn't find any obvious way to do it.  Does anyone know how I can set the default theme to Black and White so when I install the app it uses that theme?

<style name="AppTheme" parent="AppTheme.BlackAndWhite" />

**Comment by tibbi** [comment]
I dont plan changing the default theme, nor support custom app clones

**Comment by bzark** [comment]
That is fair.  Can I make a donation to get the answer?

**Comment by tibbi** [comment]
no, thats not how it works
