### ISSUE TITLE
Help end staggered software keyboards

### ISSUE THREAD

**Issue by PAI5REECHO** [SimpleMobileTools/Simple-Keyboard#74]
I would absolutely love to see this to be the first open source ortholinear keyboard for Android. It would be nice if it was made the default too in order to promote this becoming the familiar default layout for all people of the world. Staggered keyboards are not simple (https://youtu.be/Ho_CFfdsmc8?t=337), ortholinear keyboards **are** simple.

**Comment by tibbi** [comment]
it isnt on the roadmap

**Comment by PAI5REECHO** [comment]
Why can't this be added to the roadmap? Also what's the reasoning for staggering the key rows on this virtual keyboard aside from "every other keyboard does it so we do too"?

**Comment by tibbi** [comment]
well, because it makes sense and I dont want to go against the whole world
