### ISSUE TITLE
Turkish-Q language support

### ISSUE THREAD

**Issue by ondern** [SimpleMobileTools/Simple-Keyboard#76]

**Comment by ondern** [comment]
https://github.com/rkkr/simple-keyboard

This app provide Turkish-Q layout support. You can fork the code.

**Comment by Naveen3Singh** [comment]
@ondern if you'd like to provide some feedback, [here's a test APK](https://github.com/Naveen3Singh/Simple-Keyboard/releases/download/test_release_turkish_q/keyboard-prepaid-debug.apk) with Turkish-Q support added.

_Apk is meant for testing only, pls uninstall afterward._

**Comment by ondern** [comment]
Looks ok. It might be better if we can hide text panel set keyboard height and text bold

**Comment by ondern** [comment]
Looks ok. It might be better if we can hide text panel set keyboard height and text bold

**Comment by ondern** [comment]
Looks ok. It might be better if we can hide text panel set keyboard height and text bold

**Comment by suttod** [comment]
Original request closed by #83 
Numpad request is duplicate of #93 and closed by #122

**Comment by tibbi** [comment]
this has been added already
