### ISSUE TITLE
Need Enhancement Clipboard

### ISSUE THREAD

**Issue by Pantyhose-X** [SimpleMobileTools/Simple-Keyboard#92]
- [ ] Please provide the shutdown function. Turn off auto-clean Clipboard by default.

* Current Status
I forgot the "Pinned" entry, Clipboard cleans up automatically on the hour, very bad, I usually use Clipboard to save my passwords
---
- [ ] “Current” Copied items are automatically saved to Manage clipboard items

* Current Status
Manage clipboard items requires "Pinned" to be saved in Manage clipboard items

---
---

Request to create a SimpleMobileTools community here https://rvlt.gg/

**Comment by tibbi** [comment]
those arent really on the roadmap
