### ISSUE TITLE
Option to disable the clipboard-view

### ISSUE THREAD

**Issue by Synthie77** [SimpleMobileTools/Simple-Keyboard#95]
I often use my clipboard to copy passwords and didn't want them viewed in the clipboard-line. It would be great if there was a way to turn off the clipboard display. Thank you

**Comment by jonahclarsen** [comment]
I second this. I'm surprised the option to disable the clipboard bar hasn't been added yet - I imagine there are plenty of people who don't want to see their clipboard every time their keyboard pops up. For me it's mostly a screen real estate issue, but the privacy aspect is there too. If a dev can give some general directions I can try my best to implement it.
