### ISSUE TITLE
Cannot Paste from System Clipboard Into "Add a new item" of Simple-Keyboard Clipboard

### ISSUE THREAD

**Issue by code-mart** [SimpleMobileTools/Simple-Keyboard#97]
On a long press on the text box, the option to paste into the "Clip text" box appears disabled.

**Comment by tibbi** [comment]
can you send a screenshot of what you mean? That field is a casual textual field, does pasting work in other places?

**Comment by code-mart** [comment]
Yes, nevermind. I was running this in Waydroid, and I did not notice that the clipboard was not working at all. I fixed by installing pyclips and wl-clipboard, as explained in the issues below. Sorry for the trouble and thanks for the response!

https://github.com/waydroid/waydroid/issues/276
https://github.com/waydroid/waydroid/issues/309
